name: Deploy production server

on:
  push:
    branches:
      - "main"
    paths:
      - "server/**"

jobs:
  deploy-server:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "./client/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('./server/yarn.lock') }}

      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          repository: server
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Reload Production Server
        uses: ./.github/actions/restart
        with:
          port: ${{ secrets.SERVER_PORT }}
          db_port: ${{ secrets.DB_PORT }}
          db_name: ${{ secrets.DB_NAME }}
          db_host: ${{ secrets.DB_HOST }}
          db_username: ${{ secrets.DB_USERNAME }}
          db_password: ${{ secrets.DB_PASSWORD }}
          redis_host: ${{ secrets.REDIS_HOST }}
          redis_port: ${{ secrets.REDIS_PORT }}
          redis_password: ${{ secrets.REDIS_PASSWORD }}
          jwt_secret_key: ${{ secrets.JWT_SECRET_KEY }}
          refresh_jwt_secret_key: ${{ secrets.REFRESH_JWT_SECRET_KEY }}
          expire_jwt_secret_key: ${{ secrets.EXPIRE_JWT_SECRET_KEY }}
          expire_refresh_jwt_secret_key: ${{ secrets.EXPIRE_REFRESH_JWT_SECRET_KEY }}
          server_name: ${{ secrets.SERVER_NAME }}
